<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-TA6EE9O" name="com.udemy.pageclasses.ZapposTestRunner2" tests="3" failures="1" timestamp="17 May 2020 05:50:22 GMT" time="135.995" errors="0">
  <testcase name="runScenario" time="40.300" classname="com.udemy.pageclasses.ZapposTestRunner2">
    <failure type="java.lang.AssertionError" message="expected [https://www.zappo.com/] but found [https://www.zappos.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.zappo.com/] but found [https://www.zappos.com/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.udemy.pageclasses.ZapposStepDefn.user_Clicked_on_Sigin_and_Navigate_to_Login_Page(ZapposStepDefn.java:52)
at âœ½.User Clicked on Sigin and Navigate to Login Page(file:///D:/Projects/JavaProjects/LearnCucumber/src/test/java/com/udemy/pageclasses/zappostest.feature:5)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="35.040" classname="com.udemy.pageclasses.ZapposTestRunner2"/>
  <testcase name="runScenario" time="60.655" classname="com.udemy.pageclasses.ZapposTestRunner2"/>
</testsuite> <!-- com.udemy.pageclasses.ZapposTestRunner2 -->
